# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(max_length=255)),
                ('userName', models.CharField(max_length=255)),
                ('userPassWord', models.CharField(max_length=255)),
                ('quizDone', models.IntegerField(default=None)),
                ('quizTrack', models.FloatField(default=None)),
                ('totalScore', models.FloatField(default=None)),
            ],
        ),
    ]
