# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='studentId',
            field=models.CharField(default=59340500018, max_length=255),
            preserve_default=False,
        ),
    ]
