# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quizDone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='quizTrack',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='totalScore',
            field=models.FloatField(default=0),
        ),
    ]
