# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraauth',
            name='studentId',
            field=models.CharField(default='', max_length=255),
        ),
    ]
