# Generated by Django 2.0 on 2018-05-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn_Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='studentYear',
        ),
    ]
