# Generated by Django 2.0 on 2017-12-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='studentYear',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
