# Generated by Django 2.0.3 on 2018-10-22 00:11

import Assign_Management.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Exam_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('available', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('max_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=55)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('Pass or Fail', 'Pass or Fail'), ('Scoring', 'Scoring')], default='Scoring', max_length=100)),
                ('text_template_content', models.TextField(blank=True, null=True)),
                ('text_testcode_content', models.TextField()),
                ('text_testcase_content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Exam_Quizes',
            },
        ),
        migrations.CreateModel(
            name='Exam_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passOrFail', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_score', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Uploadfile', models.FileField(upload_to=Assign_Management.models.callable_path)),
                ('score', models.FloatField(blank=True, default=0.0, null=True)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Uploadfile', models.FileField(upload_to=Assign_Management.models.callable_path)),
                ('score', models.FloatField(blank=True, default=0.0, null=True)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
