# Generated by Django 2.0 on 2018-04-24 04:45

import Assign_Management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='Uploadfile',
            field=models.FileField(upload_to=Assign_Management.models.callable_path),
        ),
        migrations.AlterField(
            model_name='upload',
            name='fileUpload',
            field=models.FileField(upload_to='cccf'),
        ),
    ]
