# Generated by Django 2.0 on 2018-05-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Class_Management', '0001_initial'),
        ('Assign_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class_Management.ClassRoom'),
        ),
        migrations.AddField(
            model_name='upload',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class_Management.Quiz'),
        ),
        migrations.AddField(
            model_name='upload',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class_Management.QuizScore'),
        ),
    ]
