# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 08:44
from __future__ import unicode_literals

import Assign_Management.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0002_upload_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='Uploadfile',
            field=models.FileField(storage=Assign_Management.storage.OverwriteStorage(), upload_to='file_uploads'),
        ),
    ]
