# Generated by Django 2.0 on 2018-08-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0003_auto_20180813_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_score',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code', to='Assign_Management.Exam_Upload'),
        ),
    ]
