# Generated by Django 2.0.3 on 2018-10-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0003_auto_20181022_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='uploadIPv4',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
