# Generated by Django 2.0 on 2018-05-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0003_upload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Class_Management.QuizScore'),
        ),
    ]
