# Generated by Django 2.0 on 2018-08-07 09:24

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0003_auto_20180805_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_tracker',
            name='picked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='exam_tracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
