# Generated by Django 2.0 on 2017-12-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0011_quizscore_code'),
        ('Assign_Management', '0003_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='classroom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Class_Management.ClassRoom'),
            preserve_default=False,
        ),
    ]
