# Generated by Django 2.0 on 2018-01-01 04:49

import Assign_Management.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0004_upload_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='fileUpload',
            field=models.FileField(storage=Assign_Management.storage.OverwriteStorage(), upload_to='file_uploads'),
        ),
    ]
