# Generated by Django 2.0 on 2018-05-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0004_auto_20180501_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
