# Generated by Django 2.0 on 2018-08-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0004_auto_20180807_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_data',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='exam_quiz',
            name='hint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exam_quiz',
            name='title',
            field=models.CharField(blank=True, max_length=55, unique=True),
        ),
    ]
