# Generated by Django 2.0.3 on 2018-10-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0005_upload_testresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='classroom',
        ),
    ]
