# Generated by Django 2.0 on 2018-08-11 11:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0005_auto_20180811_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_tracker',
            name='picked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
    ]
