# Generated by Django 2.0 on 2018-05-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0005_auto_20180502_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
