# Generated by Django 2.0 on 2018-08-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0003_auto_20180811_1844'),
        ('Assign_Management', '0006_auto_20180811_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_quiz',
            name='exam',
        ),
        migrations.AddField(
            model_name='exam_quiz',
            name='classroom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Class_Management.ClassRoom'),
            preserve_default=False,
        ),
    ]
