# Generated by Django 2.0.3 on 2018-10-28 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0006_remove_category_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='comma is disallowed.', regex='^[^,]*$')]),
        ),
    ]
