# Generated by Django 2.0 on 2018-05-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0006_auto_20180509_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='fileUpload',
        ),
    ]
