# Generated by Django 2.0.3 on 2018-10-28 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0007_auto_20181028_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='comma is disallowed.', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
