# Generated by Django 2.0 on 2018-08-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0007_auto_20180812_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_quiz',
            name='available',
        ),
        migrations.RemoveField(
            model_name='exam_quiz',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='exam_quiz',
            name='hint',
        ),
    ]
