# Generated by Django 2.0.3 on 2018-10-28 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0008_auto_20181028_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='comma is disallowed.', regex='^[^,]*$')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='comma is disallowed.', regex='^[^,]*$')]),
        ),
    ]
