# Generated by Django 2.0.3 on 2018-10-29 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0009_auto_20181028_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='comma is disallowed.', regex='^[^,]*$')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='comma is disallowed.', regex='^[^,]*$')]),
        ),
    ]
