# Generated by Django 2.0.3 on 2018-10-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assign_Management', '0011_auto_20181031_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='exam_quiz',
            options={'ordering': ('-title',), 'verbose_name_plural': 'Exam_Quizes'},
        ),
        migrations.AlterModelOptions(
            name='exam_score',
            options={'ordering': ('-user',)},
        ),
        migrations.AlterModelOptions(
            name='exam_tracker',
            options={'ordering': ('-user',)},
        ),
        migrations.AlterModelOptions(
            name='exam_upload',
            options={'ordering': ('-title',)},
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ('-user', '-quiz', '-score', '-title')},
        ),
    ]
