# Generated by Django 2.0 on 2017-12-23 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Class_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztracker',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiztimer',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class_Management.ClassRoom'),
        ),
        migrations.AddField(
            model_name='quiztimer',
            name='quizId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class_Management.Quiz'),
        ),
        migrations.AddField(
            model_name='quiztimer',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizstatus',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class_Management.ClassRoom'),
        ),
        migrations.AddField(
            model_name='quizstatus',
            name='quizId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class_Management.Quiz'),
        ),
        migrations.AddField(
            model_name='quizstatus',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizscore',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class_Management.ClassRoom'),
        ),
        migrations.AddField(
            model_name='quizscore',
            name='quizId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class_Management.Quiz'),
        ),
        migrations.AddField(
            model_name='quizscore',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class_Management.ClassRoom'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
