# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='hint',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
