# Generated by Django 2.0.3 on 2018-10-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0002_auto_20181022_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='quizes',
            field=models.ManyToManyField(blank=True, to='Class_Management.Quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quizTitle',
            field=models.CharField(blank=True, max_length=55, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='classroom',
        ),
    ]
