# Generated by Django 2.0 on 2018-08-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0002_auto_20180801_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='rank',
            field=models.CharField(choices=[(0, 'Bronze'), (1, 'Silver'), (2, 'Gold'), (3, 'Platinum'), (4, 'Diamond'), (5, 'Master'), (6, 'Challenger')], default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='rank',
            name='fixture',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='mode',
            field=models.CharField(choices=[('Pass or Fail', 'Pass or Fail'), ('Scoring', 'Scoring')], default='Scoring', max_length=100),
        ),
    ]
