# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0002_quiz_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='hint',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
