# Generated by Django 2.0 on 2018-08-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0002_auto_20180805_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='hint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quizTitle',
            field=models.CharField(blank=True, max_length=55, unique=True),
        ),
    ]
