# Generated by Django 2.0 on 2017-12-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0003_quizscore_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizscore',
            name='testCase1',
        ),
        migrations.RemoveField(
            model_name='quizscore',
            name='testCase10',
        ),
        migrations.RemoveField(
            model_name='quizscore',
            name='testCase2',
        ),
        migrations.RemoveField(
            model_name='quizscore',
            name='testCase3',
        ),
        migrations.RemoveField(
            model_name='quizscore',
            name='testCase4',
        ),
        migrations.RemoveField(
            model_name='quizscore',
            name='testCase5',
        ),
        migrations.RemoveField(
            model_name='quizscore',
            name='testCase6',
        ),
        migrations.RemoveField(
            model_name='quizscore',
            name='testCase7',
        ),
        migrations.RemoveField(
            model_name='quizscore',
            name='testCase8',
        ),
        migrations.RemoveField(
            model_name='quizscore',
            name='testCase9',
        ),
    ]
