# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Class_Management', '0003_auto_20171127_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='className',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quizDetail',
            field=models.TextField(),
        ),
    ]
