# Generated by Django 2.0.3 on 2018-10-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0004_auto_20181023_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='quizes',
            field=models.ManyToManyField(blank=True, to='Class_Management.Quiz'),
        ),
    ]
