# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0004_auto_20171127_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=255)),
                ('title', models.CharField(choices=[('Teacher', 'Teacher'), ('TA', 'TA')], max_length=100)),
            ],
        ),
    ]
