# Generated by Django 2.0 on 2017-12-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0004_auto_20171224_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztimer',
            name='timer',
        ),
        migrations.AddField(
            model_name='quiztimer',
            name='time_to_stop',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
