# Generated by Django 2.0.3 on 2018-10-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0006_auto_20181023_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='text_testcode_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
