# Generated by Django 2.0 on 2017-12-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0006_auto_20171225_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztracker',
            name='quizDoneCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
