# Generated by Django 2.0 on 2018-05-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0006_auto_20180506_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Assign_Management.Upload'),
        ),
    ]
