# Generated by Django 2.0 on 2018-05-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0007_auto_20180507_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Assign_Management.Upload'),
        ),
    ]
