# Generated by Django 2.0 on 2018-05-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0008_auto_20180507_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='code',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='Assign_Management.Upload'),
        ),
    ]
