# Generated by Django 2.0 on 2017-12-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0008_quiztimer_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizTitle',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
