# Generated by Django 2.0 on 2017-12-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0009_auto_20171226_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='max_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiztracker',
            name='quizDoneCount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
