# Generated by Django 2.0.3 on 2018-10-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0010_auto_20181031_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('quizTitle', 'category', '-available'), 'verbose_name_plural': 'Quizes'},
        ),
    ]
