# Generated by Django 2.0 on 2017-12-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0010_auto_20171226_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
