# Generated by Django 2.0.3 on 2018-10-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0011_auto_20181031_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('quizTitle', 'category', 'available'), 'verbose_name_plural': 'Quizes'},
        ),
    ]
