# Generated by Django 2.0 on 2018-05-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0011_auto_20180515_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='max_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='passOrFail',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='total_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
