# Generated by Django 2.0 on 2018-01-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0011_quizscore_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztracker',
            name='userScore',
            field=models.FloatField(default=0),
        ),
    ]
