# Generated by Django 2.0 on 2018-01-03 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0012_quiztracker_userscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztracker',
            name='userScore',
        ),
        migrations.AlterField(
            model_name='quiztracker',
            name='quizDoneCount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
