# Generated by Django 2.0.3 on 2018-10-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0012_auto_20181031_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('available', 'quizTitle', 'category'), 'verbose_name_plural': 'Quizes'},
        ),
    ]
