# Generated by Django 2.0 on 2018-05-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0012_auto_20180516_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='ta',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
    ]
