# Generated by Django 2.0 on 2018-05-17 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Class_Management', '0013_auto_20180517_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='ta',
            field=models.ManyToManyField(related_name='ta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
