# Generated by Django 2.0 on 2018-05-17 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0014_auto_20180517_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='ta',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='user',
            field=models.ManyToManyField(blank=True, default=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator', to=settings.AUTH_USER_MODEL), related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
