# Generated by Django 2.0 on 2018-01-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0014_auto_20180103_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztracker',
            name='userScore',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quiztracker',
            name='quizDoneCount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
