# Generated by Django 2.0 on 2018-01-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0017_auto_20180103_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztracker',
            name='userScore',
        ),
        migrations.AlterField(
            model_name='quiztracker',
            name='quizDoneCount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
