# Generated by Django 2.0 on 2018-01-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0019_auto_20180103_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztimer',
            name='timer',
            field=models.IntegerField(null=True),
        ),
    ]
