# Generated by Django 2.0 on 2018-01-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0020_auto_20180110_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztimer',
            name='timer_stop',
            field=models.DateTimeField(null=True),
        ),
    ]
