# Generated by Django 2.0 on 2018-01-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_Management', '0021_quiztimer_timer_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztimer',
            name='timer_stop',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
